name: CI

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_CHAT_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_CHAT_DEPLOYMENT }}
      AZURE_OPENAI_SYSTEM_PROMPT: ${{ secrets.AZURE_OPENAI_SYSTEM_PROMPT }}
      BING_SEARCH_V7_ENDPOINT: ${{ secrets.BING_SEARCH_V7_ENDPOINT }}
      BING_SEARCH_V7_KEY: ${{ secrets.BING_SEARCH_V7_KEY }}
      GOOGLE_SEARCH_ENDPOINT: ${{ secrets.GOOGLE_SEARCH_ENDPOINT }}
      GOOGLE_SEARCH_KEY: ${{ secrets.GOOGLE_SEARCH_KEY }}
      GOOGLE_SEARCH_ENGINE_ID: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish cycod for multiple platforms (verification)
      run: |
        dotnet publish src/cycod/cycod.csproj -c Release -r win-x64
        dotnet publish src/cycod/cycod.csproj -c Release -r linux-x64
        dotnet publish src/cycod/cycod.csproj -c Release -r osx-x64

    - name: Publish cycodt for multiple platforms (verification)
      run: |
        dotnet publish src/cycodt/cycodt.csproj -c Release -r win-x64
        dotnet publish src/cycodt/cycodt.csproj -c Release -r linux-x64
        dotnet publish src/cycodt/cycodt.csproj -c Release -r osx-x64
        
    - name: Publish cycodmd for multiple platforms (verification)
      run: |
        dotnet publish src/cycodmd/cycodmd.csproj -c Release -r win-x64
        dotnet publish src/cycodmd/cycodmd.csproj -c Release -r linux-x64
        dotnet publish src/cycodmd/cycodmd.csproj -c Release -r osx-x64
    
    - name: Test
      run: dotnet test --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults
    
    - name: Run cycodt tests
      run: |
        export PATH=$PATH:$(pwd)/src/cycod/bin/Release/net9.0:$(pwd)/src/cycodt/bin/Release/net9.0:$(pwd)/src/cycodmd/bin/Release/net9.0
        which cycod
        which cycodmd
        which cycodt
        cycodt run --output-file ./TestResults/test-results-cycodt.trx
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()  # Upload test results even if tests fail
      with:
        name: test-results
        path: ./TestResults/*.trx
    
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()  # Run this step even if previous steps failed
      with:
        name: .NET Tests
        path: ./TestResults/*.trx
        reporter: dotnet-trx
        fail-on-error: false
    
    - name: Upload cycod build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cycod-build
        path: |
          src/cycod/bin/Release/net9.0/
          src/cycod/bin/Release/net9.0/win-x64/publish/
          src/cycod/bin/Release/net9.0/linux-x64/publish/
          src/cycod/bin/Release/net9.0/osx-x64/publish/
    
    - name: Upload cycodt build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cycodt-build
        path: |
          src/cycodt/bin/Release/net9.0/
          src/cycodt/bin/Release/net9.0/win-x64/publish/
          src/cycodt/bin/Release/net9.0/linux-x64/publish/
          src/cycodt/bin/Release/net9.0/osx-x64/publish/
          
    - name: Upload cycodmd build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cycodmd-build
        path: |
          src/cycodmd/bin/Release/net9.0/
          src/cycodmd/bin/Release/net9.0/win-x64/publish/
          src/cycodmd/bin/Release/net9.0/linux-x64/publish/
          src/cycodmd/bin/Release/net9.0/osx-x64/publish/