name: CI

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish for multiple platforms (verification)
      run: |
        dotnet publish src/chatx.csproj -c Release -r win-x64 --no-build
        dotnet publish src/chatx.csproj -c Release -r linux-x64 --no-build
        dotnet publish src/chatx.csproj -c Release -r osx-x64 --no-build
    
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()  # Upload test results even if tests fail
      with:
        name: test-results
        path: ./TestResults/*.trx
    
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()  # Run this step even if previous steps failed
      with:
        name: .NET Tests
        path: ./TestResults/*.trx
        reporter: dotnet-trx
        fail-on-error: false
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chatx-build
        path: |
          src/bin/Release/net8.0/
          src/bin/Release/net8.0/win-x64/publish/
          src/bin/Release/net8.0/linux-x64/publish/
          src/bin/Release/net8.0/osx-x64/publish/